name: Jenkins Plugin Build
on:
  push:
    # Publish `master`
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Customize the Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "repo.jenkins-ci.org", "url": "https://repo.jenkins-ci.org/public/" }, { "id": "ossrh", "url": "https://oss.sonatype.org/content/repositories/snapshots" }]'
          plugin_repositories: '[{ "id": "repo.jenkins-ci.org", "url": "https://repo.jenkins-ci.org/public/" }]'

      - name: Build with Maven
        run: |
          mvn -B -P github -C -ff -ntp -U -up package

      - name: Upload HPI File
        uses: actions/upload-artifact@v1
        with:
          name: thycotic-dsv.hpi
          path: target/thycotic-dsv.hpi
